#!/bin/sh

 NAME=testapp1
 UTILFILE=util
 DATABASE=cs348

 DB2HOME=`eval echo ~"$DB2INSTANCE"`
 DB2PATH="$DB2HOME"/sqllib

 CC=gcc
 CFLAGS=-I"$DB2PATH"/include
 LIBS="-L$DB2PATH/lib -ldb2"

 set -x

 rm -f "$NAME" "$NAME".c "$NAME".o "$NAME".bnd
 rm -f "$UTILFILE" "$UTILFILE".o "$UTILFILE".bnd

 db2 connect to "$DATABASE"
 db2 prep "$NAME".sqc bindfile
 db2 bind "$NAME".bnd
 db2 connect reset
 "$CC" "$CFLAGS" -c "$NAME".c
 "$CC" "$CFLAGS" -c "$UTILFILE".c
 "$CC" "$CFLAGS" -o "$NAME" "$NAME".o "$UTILFILE".o $LIBS
